---
# Source: prometheus-operator/templates/alertmanager/alertmanager.yaml

apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: monitoring-prometheus-oper-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
spec:
  baseImage: quay.io/prometheus/alertmanager
  version: v0.19.0
  replicas: 1
  listenLocal: false
  serviceAccountName: monitoring-prometheus-oper-alertmanager
  externalUrl: http://monitoring-prometheus-oper-alertmanager.monitoring:9093
  paused: false
  logFormat: "logfmt"
  logLevel:  "info"
  retention: "120h"
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    
