---
# Source: prometheus-operator/templates/alertmanager/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-monitoring-prometheus-oper-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
data:
  alertmanager.yaml: "Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KcmVjZWl2ZXJzOgotIG5hbWU6ICJudWxsIgpyb3V0ZToKICBncm91cF9ieToKICAtIGpvYgogIGdyb3VwX2ludGVydmFsOiA1bQogIGdyb3VwX3dhaXQ6IDMwcwogIHJlY2VpdmVyOiAibnVsbCIKICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJvdXRlczoKICAtIG1hdGNoOgogICAgICBhbGVydG5hbWU6IFdhdGNoZG9nCiAgICByZWNlaXZlcjogIm51bGwiCg=="
