---
# Source: prometheus-operator/templates/alertmanager/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-prometheus-oper-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
imagePullSecrets:
  []
  
