---
# Source: prometheus-operator/templates/exporters/kube-scheduler/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: prometheus-prometheus-oper-kube-scheduler
  namespace: monitoring
  labels:
    app: prometheus-operator-kube-scheduler
    jobLabel: kube-scheduler
    
    chart: prometheus-operator-6.20.3
    release: "prometheus"
    heritage: "Tiller"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10251
      protocol: TCP
      targetPort: 10251
  type: ClusterIP