---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.haas-440.pez.pivotal.io/library/malston/pks-control-plane
    insecure_registries: [harbor.haas-440.pez.pivotal.io]
    tag: 0.0.1

inputs:
  - name: repo
  - name: version
  - name: pks-config
  - name: kube-config

outputs:
  - name: version

run:
  path: repo/ci/tasks/install-operator/task.sh

params:
  OM_TARGET:
  OM_USERNAME:
  OM_PASSWORD:
  OM_SKIP_SSL_VALIDATION:
  FOUNDATION:
  NAMESPACE:
  RELEASE:
  VERSION:
  BOSH_UAA_CLIENT_ID:
  BOSH_UAA_CLIENT_SECRET:
  PKS_API_HOSTNAME:
  PKS_API_MONITOR_SECRET:
  CLUSTER_NAME: