---
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: monitoring-prometheus-node-exporter
  annotations:
    prometheus.io/scrape: "true"
    
  labels:     
    app: prometheus-node-exporter
    heritage: Tiller
    release: monitoring
    chart: prometheus-node-exporter-1.7.0
    jobLabel: node-exporter
    
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: metrics
  selector:
    app: prometheus-node-exporter
    release: monitoring
