---
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-prometheus-node-exporter
  labels:
    app: prometheus-node-exporter
    chart: prometheus-node-exporter-1.7.0    
    release: "monitoring"
    heritage: "Tiller"
imagePullSecrets: 
  []
  