---
# Source: prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name:  monitoring-prometheus-oper-admission
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: prometheus-operator-admission    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
