---
# Source: prometheus-operator/templates/exporters/kube-proxy/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: monitoring-prometheus-oper-kube-proxy
  namespace: monitoring
  labels:
    app: prometheus-operator-kube-proxy
    jobLabel: kube-proxy
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10249
      protocol: TCP
      targetPort: 10249
  selector:
      
    k8s-app: kube-proxy
  type: ClusterIP