---
# Source: prometheus-operator/templates/grafana/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-prometheus-oper-grafana
  namespace: monitoring
  labels:
    app: prometheus-operator-grafana
    
    chart: prometheus-operator-6.20.3
    release: "monitoring"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: grafana
      release: "monitoring"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: service
    path: "/metrics"
